INITIAL_USERS = [
    {
        "username": "masiba",
        "email": "masiba@user.com",
        "password": "123456789",
        "first_name": "maximiliano",
        "last_name": "barragan",
        "player": {
            "name": "masiba",
            "stats": {
                "tiro": 70,
                "ritmo": 30,
                "fisico": 25,
                "defensa": 73,
                "aura": 50,
            },
        },
    },
    {
        "username": "maxilu",
        "email": "maxilu@user.com",
        "password": "123456789",
        "first_name": "maximiliano",
        "last_name": "lucero",
        "player": {
            "name": "maxilu",
            "stats": {
                "tiro": 75,
                "ritmo": 60,
                "fisico": 60,
                "defensa": 50,
                "aura": 50,
            },
        },
    },
    {
        "username": "germame",
        "email": "germame@user.com",
        "password": "123456789",
        "first_name": "german",
        "last_name": "mesa",
        "player": {
            "name": "germame",
            "stats": {
                "tiro": 90,
                "ritmo": 87,
                "fisico": 80,
                "defensa": 65,
                "aura": 80,
            },
        },
    },
    {
        "username": "nachoro",
        "email": "nachoro@user.com",
        "password": "123456789",
        "first_name": "ignacio",
        "last_name": "rosas",
        "player": {
            "name": "nachoro",
            "stats": {
                "tiro": 90,
                "ritmo": 85,
                "fisico": 80,
                "defensa": 75,
                "aura": 65,
            },
        },
    },
    {
        "username": "brunofe",
        "email": "brunofe@user.com",
        "password": "123456789",
        "first_name": "bruno",
        "last_name": "fernandez",
        "player": {
            "name": "brunofe",
            "stats": {
                "tiro": 93,
                "ritmo": 70,
                "fisico": 65,
                "defensa": 60,
                "aura": 100,
            },
        },
    },
    {
        "username": "kevicr",
        "email": "kevicr@user.com",
        "password": "123456789",
        "first_name": "kevin",
        "last_name": "cristaldo",
        "player": {
            "name": "kevicr",
            "stats": {
                "tiro": 89,
                "ritmo": 95,
                "fisico": 85,
                "defensa": 43,
                "aura": 88,
            },
        },
    },
    {
        "username": "clovife",
        "email": "clovife@user.com",
        "password": "123456789",
        "first_name": "clovis",
        "last_name": "ferreira",
        "player": {
            "name": "clovife",
            "stats": {
                "tiro": 70,
                "ritmo": 65,
                "fisico": 60,
                "defensa": 70,
                "aura": 65,
            },
        },
    },
    {
        "username": "diegoma",
        "email": "diegoma@user.com",
        "password": "123456789",
        "first_name": "diego",
        "last_name": "martinez",
        "player": {
            "name": "diegoma",
            "stats": {
                "tiro": 75,
                "ritmo": 40,
                "fisico": 55,
                "defensa": 80,
                "aura": 75,
            },
        },
    },
    {
        "username": "nicolhe",
        "email": "nicolhe@user.com",
        "password": "123456789",
        "first_name": "nicolas",
        "last_name": "herrera",
        "player": {
            "name": "nicolhe",
            "stats": {
                "tiro": 90,
                "ritmo": 91,
                "fisico": 89,
                "defensa": 71,
                "aura": 88,
            },
        },
    },
    {
        "username": "santigo",
        "email": "santigo@user.com",
        "password": "123456789",
        "first_name": "santiago",
        "last_name": "barragan",
        "player": {
            "name": "santigo",
            "stats": {
                "tiro": 55,
                "ritmo": 45,
                "fisico": 40,
                "defensa": 67,
                "aura": 60,
            },
        },
    },
    {
        "username": "yaicelp",
        "email": "yaicelp@user.com",
        "password": "123456789",
        "first_name": "yaicel",
        "last_name": "pereira",
        "player": {
            "name": "yaicelp",
            "stats": {
                "tiro": 83,
                "ritmo": 85,
                "fisico": 90,
                "defensa": 75,
                "aura": 71,
            },
        },
    },
    {
        "username": "alaynsa",
        "email": "alaynsa@user.com",
        "password": "123456789",
        "first_name": "alayn",
        "last_name": "sanchez",
        "player": {
            "name": "alaynsa",
            "stats": {
                "tiro": 69,
                "ritmo": 41,
                "fisico": 35,
                "defensa": 20,
                "aura": 31,
            },
        },
    },
    {
        "username": "emiliom",
        "email": "emiliom@user.com",
        "password": "123456789",
        "first_name": "emilio",
        "last_name": "mendez",
        "player": {
            "name": "emiliom",
            "stats": {
                "tiro": 50,
                "ritmo": 45,
                "fisico": 70,
                "defensa": 79,
                "aura": 50,
            },
        },
    },
    {
        "username": "nestoet",
        "email": "nestoet@user.com",
        "password": "123456789",
        "first_name": "nestor",
        "last_name": "etcheverria",
        "player": {
            "name": "nestoet",
            "stats": {
                "tiro": 75,
                "ritmo": 85,
                "fisico": 79,
                "defensa": 67,
                "aura": 70,
            },
        },
    },
    {
        "username": "fransa",
        "email": "fransa@user.com",
        "password": "123456789",
        "first_name": "francisco",
        "last_name": "santini",
        "player": {
            "name": "fransa",
            "stats": {
                "tiro": 70,
                "ritmo": 70,
                "fisico": 79,
                "defensa": 65,
                "aura": 43,
            },
        },
    },
    {
        "username": "martigon",
        "email": "martigon@user.com",
        "password": "123456789",
        "first_name": "martin",
        "last_name": "gonzalez",
        "player": {
            "name": "martigon",
            "stats": {
                "tiro": 77,
                "ritmo": 57,
                "fisico": 66,
                "defensa": 65,
                "aura": 55,
            },
        },
    },
    {
        "username": "camilofo",
        "email": "camilofo@user.com",
        "password": "123456789",
        "first_name": "camilo",
        "last_name": "fossemale",
        "player": {
            "name": "camilofo",
            "stats": {
                "tiro": 63,
                "ritmo": 43,
                "fisico": 40,
                "defensa": 53,
                "aura": 30,
            },
        },
    },
    {
        "username": "pedroar",
        "email": "pedroar@user.com",
        "password": "123456789",
        "first_name": "pedro",
        "last_name": "arango",
        "player": {
            "name": "pedroar",
            "stats": {
                "tiro": 40,
                "ritmo": 33,
                "fisico": 47,
                "defensa": 80,
                "aura": 67,
            },
        },
    },
]


INITIAL_PLAYER_RELATIONS = {
    "masiba": {
        "maxilu": {"together": 7, "apart": 3},
        "germame": {"together": 4, "apart": 6},
        "nachoro": {"together": 5, "apart": 5},
        "kevicr": {"together": 6, "apart": 4},
        "clovife": {"together": 5, "apart": 5},
        "diegoma": {"together": 1, "apart": 9},
        "nicolhe": {"together": 5, "apart": 5},
        "santigo": {"together": 5, "apart": 5},
        "yaicelp": {"together": 1, "apart": 1},
        "alaynsa": {"together": 1, "apart": 1},
        "emiliom": {"together": 5, "apart": 5},
        "nestoet": {"together": 5, "apart": 5},
    },

    "maxilu": {
        "germame": {"together": 9, "apart": 1},
        "nachoro": {"together": 5, "apart": 5},
        "kevicr": {"together": 1, "apart": 1},
        "clovife": {"together": 1, "apart": 1},
        "diegoma": {"together": 3, "apart": 3},
        "nicolhe": {"together": 1, "apart": 1},
        "santigo": {"together": 5, "apart": 5},
        "yaicelp": {"together": 1, "apart": 1},
        "alaynsa": {"together": 1, "apart": 1},
        "emiliom": {"together": 4, "apart": 6},
        "nestoet": {"together": 1, "apart": 1},
    },

    "germame": {
        "nachoro": {"together": 5, "apart": 5},
        "kevicr": {"together": 0, "apart": 5},
        "clovife": {"together": 1, "apart": 1},
        "diegoma": {"together": 5, "apart": 5},
        "nicolhe": {"together": 1, "apart": 1},
        "santigo": {"together": 1, "apart": 1},
        "yaicelp": {"together": 1, "apart": 1},
        "alaynsa": {"together": 1, "apart": 1},
        "emiliom": {"together": 7, "apart": 3},
        "nestoet": {"together": 1, "apart": 1},
    },

    "nachoro": {
        "kevicr": {"together": 1, "apart": 1},
        "clovife": {"together": 1, "apart": 1},
        "diegoma": {"together": 5, "apart": 5},
        "nicolhe": {"together": 1, "apart": 1},
        "santigo": {"together": 1, "apart": 1},
        "yaicelp": {"together": 1, "apart": 1},
        "alaynsa": {"together": 1, "apart": 1},
        "emiliom": {"together": 0, "apart": 6},
        "nestoet": {"together": 1, "apart": 1},
    },

    "kevicr": {
        "clovife": {"together": 10, "apart": 0},
        "diegoma": {"together": 5, "apart": 5},
        "nicolhe": {"together": 3, "apart": 7},
        "santigo": {"together": 1, "apart": 1},
        "yaicelp": {"together": 1, "apart": 1},
        "alaynsa": {"together": 1, "apart": 1},
        "emiliom": {"together": 6, "apart": 4},
        "nestoet": {"together": 1, "apart": 1},
    },

    "clovife": {
        "diegoma": {"together": 5, "apart": 5},
        "nicolhe": {"together": 6, "apart": 4},
        "santigo": {"together": 5, "apart": 5},
        "yaicelp": {"together": 1, "apart": 1},
        "alaynsa": {"together": 1, "apart": 1},
        "emiliom": {"together": 5, "apart": 5},
        "nestoet": {"together": 1, "apart": 1},
    },

    "diegoma": {
        "nicolhe": {"together": 6, "apart": 4},
        "santigo": {"together": 5, "apart": 5},
        "yaicelp": {"together": 5, "apart": 5},
        "alaynsa": {"together": 5, "apart": 5},
        "emiliom": {"together": 8, "apart": 2},
        "nestoet": {"together": 1, "apart": 1},
    },

}
